In [ ]:
import sys
from pathlib import Path
sys.path.append(str(Path.cwd().parent))

import utils as uti
import visualizacoes as vis
import analise_descritiva as ad
import limpeza as lpz
import outliers as out
import imputacao as imp
import format as frm

# Dados Brutos

In [2]:
dados_brutos, metadados, variaveis, n_casas_decimais = uti.dados(r"data\in\dados_brutos.xlsx", original=True)

In [ ]:
ad_dados_brutos = ad.analise_descritiva(dados_brutos)

# Dados Prontos

In [3]:
dados_prontos, metadados, variaveis = lpz.prep_brutos(dados_brutos)

Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\dados_prontos20260420_162930.xlsx

In [ ]:
ad_dados_prontos = ad.analise_descritiva(dados_prontos)

# Dados Limpos

In [4]:
dados_limpos, metadados, variaveis = lpz.limpeza(dados_prontos, metadados=metadados, variaveis=variaveis)

Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\dados_limpos20260420_162935.xlsx

In [5]:
ad_limpos = ad.analise_descritiva(dados_limpos)

Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\describe20260420_162940.xlsx

c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['149.3' '192.2' '4.0' '46.0' '74.0' '171.0' '1650.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['102.2' '196.5' '1.0' '9.0' '21.0' '92.0' '1200.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['7.3' '0.3' '4.7' '7.2' '7.3' '7.5' '8.1']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['63.6' '30.9' '16.0' '44.0' '57.5' '75.8' '224.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['12.5' '11.7' '0.0' '7.0' '10.0' '13.0' '120.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['9.1' '5.7' '2.3' '6.3' '7.8' '10.2' '84.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['3.2' '1.6' '0.0' '2.1' '3.1' '4.3' '9.5']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['45.3' '31.0' '5.0' '30.0' '39.0' '51.0' '328.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['55.2' '23.8' '10.0' '40.0' '50.0' '64.0' '174.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['2.39' '2.74' '0.09' '0.83' '1.28' '2.83' '26.00']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.21' '0.21' '0.01' '0.11' '0.15' '0.22' '2.36']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['325.7' '180.5' '60.0' '202.5' '283.0' '403.0' '1438.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['10527.4' '14958.8' '57.0' '2064.0' '4964.0' '13364.0' '122480.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['23843' '53343' '0' '2200' '5400' '19000' '500000']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['36.54' '47.75' '0.00' '12.28' '25.29' '47.17' '509.64']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.314' '0.202' '0.000' '0.198' '0.280' '0.380' '1.520']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:79: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_apagar, metadados] = ''

# IQR

In [6]:
iqr = out.remove_outliers_iqr(dados_limpos, variaveis=variaveis)

Outliers detectados por IQR (Tukey):
COR: 55 outliers (limites: -141.500 a 358.500)
TURB.: 75 outliers (limites: -115.500 a 216.500)
pH: 21 outliers (limites: 6.750 a 7.950)
ALC.: 28 outliers (limites: -3.625 a 123.375)
AC.: 51 outliers (limites: -2.000 a 22.000)
O.C.: 37 outliers (limites: 0.450 a 16.050)
O.D.: 5 outliers (limites: -1.200 a 7.600)
Cl: 38 outliers (limites: -1.500 a 82.500)
DUR.: 23 outliers (limites: 4.000 a 100.000)
Fe: 53 outliers (limites: -2.163 a 5.818)
Mn: 60 outliers (limites: -0.055 a 0.385)
Cond.: 25 outliers (limites: -98.250 a 703.750)
Cianobacteria: 46 outliers (limites: -14886.000 a 30314.000)
C.F.: 57 outliers (limites: -23000.000 a 44200.000)
Clorofila: 33 outliers (limites: -40.055 a 99.505)
F: 26 outliers (limites: -0.076 a 0.654)

Total de outliers (IQR, somando todas as colunas): 633
Total de linhas com pelo menos um outlier (IQR): 269
Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\outliers_removed_iqr20260420_162955.xlsx

In [7]:
ad_iqr = ad.analise_descritiva(iqr, metadados=metadados, variaveis=variaveis)

Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\describe20260420_163014.xlsx

c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['75.6' '55.5' '4.0' '39.8' '56.0' '90.2' '307.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['32.4' '43.6' '1.0' '7.0' '13.0' '36.2' '215.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['7.2' '0.2' '6.8' '7.1' '7.2' '7.4' '7.9']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['55.1' '18.9' '21.0' '41.5' '52.0' '65.5' '117.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['9.3' '3.8' '0.0' '7.0' '9.0' '11.0' '22.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['7.1' '2.1' '3.0' '5.8' '6.8' '8.4' '15.9']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['2.7' '1.2' '0.0' '1.9' '2.6' '3.5' '7.1']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['36.1' '12.6' '5.0' '26.0' '35.0' '43.2' '80.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['47.2' '15.2' '12.0' '37.0' '46.0' '57.2' '99.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['1.41' '1.04' '0.09' '0.73' '1.04' '1.69' '5.71']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.13' '0.07' '0.01' '0.09' '0.12' '0.16' '0.36']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['276.1' '115.5' '60.0' '193.0' '259.0' '342.0' '656.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['6440.9' '6121.9' '57.0' '1926.5' '4085.0' '8251.5' '29083.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['8734' '9866' '0' '1800' '4100' '13500' '43500']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['26.37' '19.71' '0.00' '11.16' '20.46' '35.27' '86.30']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.266' '0.108' '0.000' '0.200' '0.260' '0.330' '0.630']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:79: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_apagar, metadados] = ''

In [8]:
iqr_media = imp.mean_imput(iqr, variaveis=variaveis)

iqr_mediana = imp.median_imput(dados_limpos, variaveis=variaveis)

iqr_knn = imp.knn_imput(dados_limpos, variaveis=variaveis)

Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\imput_mean20260420_163032.xlsx
Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\imput_median20260420_163032.xlsx
Valores faltantes após imputação KNN:
COR              0
TURB.            0
pH               0
ALC.             0
AC.              0
O.C.             0
O.D.             0
Cl               0
DUR.             0
Fe               0
Mn               0
Cond.            0
Cianobacteria    0
C.F.             0
Clorofila        0
F                0
dtype: int64
Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\imput_knn20260420_163032.xlsx

In [10]:
ad_iqr_media = ad.analise_descritiva(iqr_media, metadados=metadados, variaveis=variaveis)

Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\describe20260420_163204.xlsx

c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['75.6' '55.2' '4.0' '40.0' '56.0' '90.0' '307.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['32.4' '43.4' '1.0' '7.0' '13.0' '36.0' '215.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['7.2' '0.2' '6.8' '7.1' '7.2' '7.4' '7.9']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['55.1' '18.9' '21.0' '41.5' '52.0' '65.5' '117.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['9.3' '3.8' '0.0' '7.0' '9.0' '11.0' '22.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['7.1' '2.1' '3.0' '5.8' '6.8' '8.4' '15.9']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['2.7' '1.2' '0.0' '2.0' '2.7' '3.5' '7.1']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['36.1' '12.6' '5.0' '26.0' '35.0' '43.2' '80.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['47.2' '15.2' '12.0' '37.0' '46.0' '57.2' '99.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['1.41' '1.04' '0.09' '0.73' '1.04' '1.69' '5.71']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.13' '0.07' '0.01' '0.09' '0.12' '0.16' '0.36']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['276.1' '113.8' '60.0' '194.5' '261.0' '337.5' '656.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['6440.9' '6121.9' '57.0' '1926.5' '4085.0' '8251.5' '29083.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['8734' '9866' '0' '1800' '4100' '13500' '43500']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['26.37' '19.71' '0.00' '11.16' '20.46' '35.27' '86.30']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.266' '0.108' '0.000' '0.200' '0.260' '0.330' '0.630']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:79: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_apagar, metadados] = ''

In [11]:
ad_iqr_mediana = ad.analise_descritiva(iqr_mediana, metadados=metadados, variaveis=variaveis)

Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\describe20260420_163217.xlsx

c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['148.9' '191.8' '4.0' '46.0' '74.0' '171.0' '1650.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['101.8' '196.1' '1.0' '9.0' '21.0' '92.0' '1200.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['7.3' '0.3' '4.7' '7.2' '7.3' '7.5' '8.1']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['63.6' '30.9' '16.0' '44.0' '57.5' '75.8' '224.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['12.5' '11.7' '0.0' '7.0' '10.0' '13.0' '120.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['9.0' '5.6' '2.3' '6.4' '7.8' '10.0' '84.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['3.2' '1.6' '0.0' '2.1' '3.1' '4.3' '9.5']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['45.0' '30.4' '5.0' '30.0' '39.0' '50.0' '328.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['55.0' '23.4' '10.0' '40.0' '50.0' '64.0' '174.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['2.35' '2.70' '0.09' '0.84' '1.28' '2.77' '26.00']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.21' '0.20' '0.01' '0.11' '0.15' '0.21' '2.36']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['325.0' '179.1' '60.0' '203.0' '283.0' '400.2' '1438.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['10527.4' '14958.8' '57.0' '2064.0' '4964.0' '13364.0' '122480.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['23843' '53343' '0' '2200' '5400' '19000' '500000']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['36.54' '47.75' '0.00' '12.28' '25.29' '47.17' '509.64']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.314' '0.202' '0.000' '0.198' '0.280' '0.380' '1.520']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:79: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_apagar, metadados] = ''

In [12]:
ad_iqr_knn = ad.analise_descritiva(iqr_knn, metadados=metadados, variaveis=variaveis)

Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\describe20260420_163223.xlsx

c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['149.3' '191.7' '4.0' '46.0' '75.0' '171.0' '1650.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['102.2' '196.0' '1.0' '9.0' '21.5' '95.2' '1200.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['7.3' '0.3' '4.7' '7.2' '7.3' '7.5' '8.1']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['64.1' '30.5' '16.0' '44.0' '58.0' '76.0' '224.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['12.6' '11.6' '0.0' '7.0' '10.0' '13.0' '120.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['9.0' '5.6' '2.3' '6.4' '7.9' '10.0' '84.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['3.2' '1.6' '0.0' '2.1' '3.1' '4.3' '9.5']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['45.3' '30.5' '5.0' '30.0' '40.0' '51.0' '328.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['55.0' '23.5' '10.0' '40.0' '50.0' '64.0' '174.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['2.35' '2.70' '0.09' '0.82' '1.25' '2.77' '26.00']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.21' '0.21' '0.01' '0.11' '0.15' '0.22' '2.36']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['326.0' '179.2' '60.0' '203.0' '285.5' '403.0' '1438.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['10544.9' '14550.9' '57.0' '2428.0' '5175.8' '13666.2' '122480.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['22063' '50061' '0' '2000' '5000' '17662' '500000']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['36.58' '47.33' '0.00' '12.28' '25.89' '45.76' '509.64']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.328' '0.198' '0.000' '0.210' '0.290' '0.390' '1.520']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:79: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_apagar, metadados] = ''

# Z-Score

In [13]:
zscore = out.remove_outliers_zscore(dados_limpos, variaveis=variaveis)

Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\outliers_removed_zscore20260420_163232.xlsx

In [14]:
ad_zscore = ad.analise_descritiva(zscore, metadados=metadados, variaveis=variaveis)

Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\describe20260420_163242.xlsx

c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['149.3' '192.2' '4.0' '46.0' '74.0' '171.0' '1650.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['102.2' '196.5' '1.0' '9.0' '21.0' '92.0' '1200.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['7.3' '0.3' '4.7' '7.2' '7.3' '7.5' '8.1']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['63.6' '30.9' '16.0' '44.0' '57.5' '75.8' '224.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['12.5' '11.7' '0.0' '7.0' '10.0' '13.0' '120.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['9.1' '5.7' '2.3' '6.3' '7.8' '10.2' '84.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['3.2' '1.6' '0.0' '2.1' '3.1' '4.3' '9.5']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['45.3' '31.0' '5.0' '30.0' '39.0' '51.0' '328.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['55.2' '23.8' '10.0' '40.0' '50.0' '64.0' '174.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['2.39' '2.74' '0.09' '0.83' '1.28' '2.83' '26.00']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.21' '0.21' '0.01' '0.11' '0.15' '0.22' '2.36']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['325.7' '180.5' '60.0' '202.5' '283.0' '403.0' '1438.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['10527.4' '14958.8' '57.0' '2064.0' '4964.0' '13364.0' '122480.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['23843' '53343' '0' '2200' '5400' '19000' '500000']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['36.54' '47.75' '0.00' '12.28' '25.29' '47.17' '509.64']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.314' '0.202' '0.000' '0.198' '0.280' '0.380' '1.520']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:79: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_apagar, metadados] = ''

In [15]:
zscore_media = imp.mean_imput(zscore, variaveis=variaveis)

zscore_mediana = imp.median_imput(zscore, variaveis=variaveis)

zscore_knn = imp.knn_imput(zscore, variaveis=variaveis)

Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\imput_mean20260420_163302.xlsx
Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\imput_median20260420_163302.xlsx
Valores faltantes após imputação KNN:
COR              0
TURB.            0
pH               0
ALC.             0
AC.              0
O.C.             0
O.D.             0
Cl               0
DUR.             0
Fe               0
Mn               0
Cond.            0
Cianobacteria    0
C.F.             0
Clorofila        0
F                0
dtype: int64
Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\imput_knn20260420_163302.xlsx

In [16]:
ad.analise_descritiva(zscore_media, metadados=metadados, variaveis=variaveis)

Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\describe20260420_163338.xlsx

c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['149.3' '191.7' '4.0' '46.0' '75.0' '171.0' '1650.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['102.2' '196.0' '1.0' '9.0' '21.5' '95.2' '1200.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['7.3' '0.3' '4.7' '7.2' '7.3' '7.5' '8.1']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['63.6' '30.9' '16.0' '44.0' '57.5' '75.8' '224.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['12.5' '11.7' '0.0' '7.0' '10.0' '13.0' '120.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['9.1' '5.6' '2.3' '6.4' '8.0' '10.0' '84.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['3.2' '1.6' '0.0' '2.1' '3.2' '4.3' '9.5']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['45.3' '30.4' '5.0' '30.0' '40.0' '50.0' '328.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['55.2' '23.4' '10.0' '40.0' '50.0' '64.0' '174.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['2.39' '2.69' '0.09' '0.84' '1.34' '2.77' '26.00']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.21' '0.20' '0.01' '0.11' '0.15' '0.21' '2.36']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['325.7' '179.0' '60.0' '203.0' '287.0' '400.2' '1438.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['10527.4' '14958.8' '57.0' '2064.0' '4964.0' '13364.0' '122480.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['23843' '53343' '0' '2200' '5400' '19000' '500000']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['36.54' '47.75' '0.00' '12.28' '25.29' '47.17' '509.64']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.314' '0.202' '0.000' '0.198' '0.280' '0.380' '1.520']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:79: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_apagar, metadados] = ''

,count,unique,top,freq,mean,min,25%,50%,75%,max,std,Porcentagem de Dados Faltantes,Numero de Dados Faltantes,Porcentagem de Dados Corrompidos,Numero de Dados Corrompidos
Index,576.0,NaN,,NaN,,,,,,,,,,,
Data,576,NaN,,NaN,,,,,,,,,,,
data_normalizada,576,192,,3,,,,,,,,,,,
Estatistica,576,3,,192,,,,,,,,,,,
COR,576.0,NaN,NaN,NaN,149.3,4.0,46.0,75.0,171.0,1650.0,191.7,0.0,0.0,0.0,0.0
TURB.,576.0,NaN,NaN,NaN,102.2,1.0,9.0,21.5,95.2,1200.0,196.0,0.0,0.0,0.0,0.0
pH,576.0,NaN,NaN,NaN,7.3,4.7,7.2,7.3,7.5,8.1,0.3,0.0,0.0,0.0,0.0
ALC.,546.0,NaN,NaN,NaN,63.6,16.0,44.0,57.5,75.8,224.0,30.9,5.21,30.0,0.0,0.0
AC.,546.0,NaN,NaN,NaN,12.5,0.0,7.0,10.0,13.0,120.0,11.7,5.21,30.0,0.0,0.0
O.C.,576.0,NaN,NaN,NaN,9.1,2.3,6.4,8.0,10.0,84.0,5.6,0.0,0.0,0.0,0.0
O.D.,576.0,NaN,NaN,NaN,3.2,0.0,2.1,3.2,4.3,9.5,1.6,0.0,0.0,0.0,0.0
Cl,576.0,NaN,NaN,NaN,45.3,5.0,30.0,40.0,50.0,328.0,30.4,0.0,0.0,0.0,0.0
DUR.,576.0,NaN,NaN,NaN,55.2,10.0,40.0,50.0,64.0,174.0,23.4,0.0,0.0,0.0,0.0
Fe,576.0,NaN,NaN,NaN,2.39,0.09,0.84,1.34,2.77,26.00,2.69,0.0,0.0,0.0,0.0
Mn,576.0,NaN,NaN,NaN,0.21,0.01,0.11,0.15,0.21,2.36,0.20,0.0,0.0,0.0,0.0
Cond.,576.0,NaN,NaN,NaN,325.7,60.0,203.0,287.0,400.2,1438.0,179.0,0.0,0.0,0.0,0.0
Cianobacteria,534.0,NaN,NaN,NaN,10527.4,57.0,2064.0,4964.0,13364.0,122480.0,14958.8,7.29,42.0,0.0,0.0
C.F.,461.0,NaN,NaN,NaN,23843,0,2200,5400,19000,500000,53343,19.97,115.0,0.0,0.0
Clorofila,531.0,NaN,NaN,NaN,36.54,0.00,12.28,25.29,47.17,509.64,47.75,7.81,45.0,0.0,0.0
F,468.0,NaN,NaN,NaN,0.314,0.000,0.198,0.280,0.380,1.520,0.202,18.75,108.0,0.0,0.0

In [17]:
ad.analise_descritiva(zscore_mediana, metadados=metadados, variaveis=variaveis)

Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\describe20260420_163350.xlsx

c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['148.9' '191.8' '4.0' '46.0' '74.0' '171.0' '1650.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['101.8' '196.1' '1.0' '9.0' '21.0' '92.0' '1200.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['7.3' '0.3' '4.7' '7.2' '7.3' '7.5' '8.1']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['63.6' '30.9' '16.0' '44.0' '57.5' '75.8' '224.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['12.5' '11.7' '0.0' '7.0' '10.0' '13.0' '120.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['9.0' '5.6' '2.3' '6.4' '7.8' '10.0' '84.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['3.2' '1.6' '0.0' '2.1' '3.1' '4.3' '9.5']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['45.0' '30.4' '5.0' '30.0' '39.0' '50.0' '328.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['55.0' '23.4' '10.0' '40.0' '50.0' '64.0' '174.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['2.35' '2.70' '0.09' '0.84' '1.28' '2.77' '26.00']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.21' '0.20' '0.01' '0.11' '0.15' '0.21' '2.36']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['325.0' '179.1' '60.0' '203.0' '283.0' '400.2' '1438.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['10527.4' '14958.8' '57.0' '2064.0' '4964.0' '13364.0' '122480.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['23843' '53343' '0' '2200' '5400' '19000' '500000']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['36.54' '47.75' '0.00' '12.28' '25.29' '47.17' '509.64']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.314' '0.202' '0.000' '0.198' '0.280' '0.380' '1.520']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:79: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_apagar, metadados] = ''

,count,unique,top,freq,mean,min,25%,50%,75%,max,std,Porcentagem de Dados Faltantes,Numero de Dados Faltantes,Porcentagem de Dados Corrompidos,Numero de Dados Corrompidos
Index,576.0,NaN,,NaN,,,,,,,,,,,
Data,576,NaN,,NaN,,,,,,,,,,,
data_normalizada,576,192,,3,,,,,,,,,,,
Estatistica,576,3,,192,,,,,,,,,,,
COR,576.0,NaN,NaN,NaN,148.9,4.0,46.0,74.0,171.0,1650.0,191.8,0.0,0.0,0.0,0.0
TURB.,576.0,NaN,NaN,NaN,101.8,1.0,9.0,21.0,92.0,1200.0,196.1,0.0,0.0,0.0,0.0
pH,576.0,NaN,NaN,NaN,7.3,4.7,7.2,7.3,7.5,8.1,0.3,0.0,0.0,0.0,0.0
ALC.,546.0,NaN,NaN,NaN,63.6,16.0,44.0,57.5,75.8,224.0,30.9,5.21,30.0,0.0,0.0
AC.,546.0,NaN,NaN,NaN,12.5,0.0,7.0,10.0,13.0,120.0,11.7,5.21,30.0,0.0,0.0
O.C.,576.0,NaN,NaN,NaN,9.0,2.3,6.4,7.8,10.0,84.0,5.6,0.0,0.0,0.0,0.0
O.D.,576.0,NaN,NaN,NaN,3.2,0.0,2.1,3.1,4.3,9.5,1.6,0.0,0.0,0.0,0.0
Cl,576.0,NaN,NaN,NaN,45.0,5.0,30.0,39.0,50.0,328.0,30.4,0.0,0.0,0.0,0.0
DUR.,576.0,NaN,NaN,NaN,55.0,10.0,40.0,50.0,64.0,174.0,23.4,0.0,0.0,0.0,0.0
Fe,576.0,NaN,NaN,NaN,2.35,0.09,0.84,1.28,2.77,26.00,2.70,0.0,0.0,0.0,0.0
Mn,576.0,NaN,NaN,NaN,0.21,0.01,0.11,0.15,0.21,2.36,0.20,0.0,0.0,0.0,0.0
Cond.,576.0,NaN,NaN,NaN,325.0,60.0,203.0,283.0,400.2,1438.0,179.1,0.0,0.0,0.0,0.0
Cianobacteria,534.0,NaN,NaN,NaN,10527.4,57.0,2064.0,4964.0,13364.0,122480.0,14958.8,7.29,42.0,0.0,0.0
C.F.,461.0,NaN,NaN,NaN,23843,0,2200,5400,19000,500000,53343,19.97,115.0,0.0,0.0
Clorofila,531.0,NaN,NaN,NaN,36.54,0.00,12.28,25.29,47.17,509.64,47.75,7.81,45.0,0.0,0.0
F,468.0,NaN,NaN,NaN,0.314,0.000,0.198,0.280,0.380,1.520,0.202,18.75,108.0,0.0,0.0

In [18]:
ad.analise_descritiva(zscore_knn, metadados=metadados, variaveis=variaveis)

Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\describe20260420_163359.xlsx

c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['149.3' '191.7' '4.0' '46.0' '75.0' '171.0' '1650.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['102.2' '196.0' '1.0' '9.0' '21.5' '95.2' '1200.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['7.3' '0.3' '4.7' '7.2' '7.3' '7.5' '8.1']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['64.1' '30.5' '16.0' '44.0' '58.0' '76.0' '224.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['12.6' '11.6' '0.0' '7.0' '10.0' '13.0' '120.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['9.0' '5.6' '2.3' '6.4' '7.9' '10.0' '84.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['3.2' '1.6' '0.0' '2.1' '3.1' '4.3' '9.5']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['45.3' '30.5' '5.0' '30.0' '40.0' '51.0' '328.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['55.0' '23.5' '10.0' '40.0' '50.0' '64.0' '174.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['2.35' '2.70' '0.09' '0.82' '1.25' '2.77' '26.00']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.21' '0.21' '0.01' '0.11' '0.15' '0.22' '2.36']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['326.0' '179.2' '60.0' '203.0' '285.5' '403.0' '1438.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['10544.9' '14550.9' '57.0' '2428.0' '5175.8' '13666.2' '122480.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['22063' '50061' '0' '2000' '5000' '17662' '500000']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['36.58' '47.33' '0.00' '12.28' '25.89' '45.76' '509.64']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.328' '0.198' '0.000' '0.210' '0.290' '0.390' '1.520']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:79: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_apagar, metadados] = ''

,count,unique,top,freq,mean,min,25%,50%,75%,max,std,Porcentagem de Dados Faltantes,Numero de Dados Faltantes,Porcentagem de Dados Corrompidos,Numero de Dados Corrompidos
Index,576.0,NaN,,NaN,,,,,,,,,,,
Data,576,NaN,,NaN,,,,,,,,,,,
data_normalizada,576,192,,3,,,,,,,,,,,
Estatistica,576,3,,192,,,,,,,,,,,
COR,576.0,NaN,NaN,NaN,149.3,4.0,46.0,75.0,171.0,1650.0,191.7,0.0,0.0,0.0,0.0
TURB.,576.0,NaN,NaN,NaN,102.2,1.0,9.0,21.5,95.2,1200.0,196.0,0.0,0.0,0.0,0.0
pH,576.0,NaN,NaN,NaN,7.3,4.7,7.2,7.3,7.5,8.1,0.3,0.0,0.0,0.0,0.0
ALC.,576.0,NaN,NaN,NaN,64.1,16.0,44.0,58.0,76.0,224.0,30.5,0.0,0.0,0.0,0.0
AC.,576.0,NaN,NaN,NaN,12.6,0.0,7.0,10.0,13.0,120.0,11.6,0.0,0.0,0.0,0.0
O.C.,576.0,NaN,NaN,NaN,9.0,2.3,6.4,7.9,10.0,84.0,5.6,0.0,0.0,0.0,0.0
O.D.,576.0,NaN,NaN,NaN,3.2,0.0,2.1,3.1,4.3,9.5,1.6,0.0,0.0,0.0,0.0
Cl,576.0,NaN,NaN,NaN,45.3,5.0,30.0,40.0,51.0,328.0,30.5,0.0,0.0,0.0,0.0
DUR.,576.0,NaN,NaN,NaN,55.0,10.0,40.0,50.0,64.0,174.0,23.5,0.0,0.0,0.0,0.0
Fe,576.0,NaN,NaN,NaN,2.35,0.09,0.82,1.25,2.77,26.00,2.70,0.0,0.0,0.0,0.0
Mn,576.0,NaN,NaN,NaN,0.21,0.01,0.11,0.15,0.22,2.36,0.21,0.0,0.0,0.0,0.0
Cond.,576.0,NaN,NaN,NaN,326.0,60.0,203.0,285.5,403.0,1438.0,179.2,0.0,0.0,0.0,0.0
Cianobacteria,576.0,NaN,NaN,NaN,10544.9,57.0,2428.0,5175.8,13666.2,122480.0,14550.9,0.0,0.0,0.0,0.0
C.F.,576.0,NaN,NaN,NaN,22063,0,2000,5000,17662,500000,50061,0.0,0.0,0.0,0.0
Clorofila,576.0,NaN,NaN,NaN,36.58,0.00,12.28,25.89,45.76,509.64,47.33,0.0,0.0,0.0,0.0
F,576.0,NaN,NaN,NaN,0.328,0.000,0.210,0.290,0.390,1.520,0.198,0.0,0.0,0.0,0.0

# LOF

## ERROS

In [ ]:
# lof_iqr_media = out.remove_outliers_lof(iqr_media, variaveis=variaveis)

# lof_iqr_mediana = out.remove_outliers_lof(iqr_mediana, variaveis=variaveis)

# lof_zscore_media = out.remove_outliers_lof(zscore_media, variaveis=variaveis)

# lof_zscore_mediana = out.remove_outliers_lof(zscore_mediana, variaveis=variaveis)

"""MENSAGEM DE ERRO: 
ValueError: Input X contains NaN.
LocalOutlierFactor does not accept missing values encoded as NaN natively. For supervised learning, 
you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor 
which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, 
for instance by using an imputer transformer in a pipeline or drop samples with missing values. 
See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators 
that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values 
"""

'MENSAGEM DE ERRO'

# Remoção de outliers

In [ ]:
lof_iqr_knn = out.remove_outliers_lof(iqr_knn, variaveis=variaveis)
ad.analise_descritiva(lof_iqr_knn)

Número de outliers detectados pelo LOF: 52
Score LOF mínimo: -5.063
Score LOF máximo: -0.939
Média dos scores LOF: -1.156
Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\outliers_removed_lof20260420_165958.xlsx

In [ ]:
lof_zscore_knn = out.remove_outliers_lof(zscore_knn, variaveis=variaveis)
ad.analise_descritiva(lof_zscore_knn)

Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\describe20260420_163946.xlsx

c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['148.0' '185.2' '4.0' '46.0' '74.5' '177.0' '1220.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['102.6' '195.9' '1.0' '9.0' '21.0' '99.5' '1200.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['7.3' '0.3' '4.7' '7.2' '7.3' '7.5' '8.1']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['62.6' '28.5' '16.0' '44.0' '58.0' '74.2' '224.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['12.5' '11.2' '0.0' '7.0' '10.0' '13.0' '120.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['8.9' '5.6' '3.0' '6.3' '7.8' '9.8' '84.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['3.2' '1.6' '0.0' '2.1' '3.1' '4.3' '9.5']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['44.8' '30.7' '5.0' '30.0' '39.0' '50.0' '328.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['54.1' '22.4' '10.0' '40.0' '50.0' '62.0' '170.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['2.33' '2.56' '0.09' '0.81' '1.28' '2.80' '18.00']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.20' '0.19' '0.01' '0.10' '0.15' '0.21' '1.64']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['318.5' '172.6' '60.0' '202.0' '281.5' '394.2' '1438.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['8556.8' '9554.0' '57.0' '2353.0' '4656.5' '12010.2' '45955.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['16426' '33489' '100' '2000' '4200' '17000' '250850']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['31.69' '30.91' '0.00' '11.61' '22.32' '39.71' '274.53']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.334' '0.198' '0.000' '0.220' '0.290' '0.390' '1.520']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:79: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_apagar, metadados] = ''

# Imputação

In [ ]:
media_lof_iqr_knn = imp.mean_imput(lof_iqr_knn, variaveis=variaveis)
ad.analise_descritiva(media_lof_iqr_knn)

Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\imput_mean20260420_165007.xlsx

In [34]:
mediana_lof_iqr_knn = imp.median_imput(lof_iqr_knn, variaveis=variaveis)
ad.analise_descritiva(mediana_lof_iqr_knn)

Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\imput_median20260420_165042.xlsx
Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\describe20260420_165042.xlsx

c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['148.0' '185.2' '4.0' '46.0' '74.5' '177.0' '1220.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['102.6' '195.9' '1.0' '9.0' '21.0' '99.5' '1200.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['7.3' '0.3' '4.7' '7.2' '7.3' '7.5' '8.1']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['62.6' '28.5' '16.0' '44.0' '58.0' '74.2' '224.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['12.5' '11.2' '0.0' '7.0' '10.0' '13.0' '120.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['8.9' '5.6' '3.0' '6.3' '7.8' '9.8' '84.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['3.2' '1.6' '0.0' '2.1' '3.1' '4.3' '9.5']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['44.8' '30.7' '5.0' '30.0' '39.0' '50.0' '328.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['54.1' '22.4' '10.0' '40.0' '50.0' '62.0' '170.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['2.33' '2.56' '0.09' '0.81' '1.28' '2.80' '18.00']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.20' '0.19' '0.01' '0.10' '0.15' '0.21' '1.64']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['318.5' '172.6' '60.0' '202.0' '281.5' '394.2' '1438.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['8556.8' '9554.0' '57.0' '2353.0' '4656.5' '12010.2' '45955.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['16426' '33489' '100' '2000' '4200' '17000' '250850']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['31.69' '30.91' '0.00' '11.61' '22.32' '39.71' '274.53']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.334' '0.198' '0.000' '0.220' '0.290' '0.390' '1.520']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:79: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_apagar, metadados] = ''

,count,unique,top,freq,mean,min,25%,50%,75%,max,std,Porcentagem de Dados Faltantes,Numero de Dados Faltantes,Porcentagem de Dados Corrompidos,Numero de Dados Corrompidos
Index,524.0,NaN,,NaN,,,,,,,,,,,
Data,524,NaN,,NaN,,,,,,,,,,,
data_normalizada,524,180,,3,,,,,,,,,,,
Estatistica,524,3,,176,,,,,,,,,,,
COR,524.0,NaN,NaN,NaN,148.0,4.0,46.0,74.5,177.0,1220.0,185.2,0.0,0.0,0.0,0.0
TURB.,524.0,NaN,NaN,NaN,102.6,1.0,9.0,21.0,99.5,1200.0,195.9,0.0,0.0,0.0,0.0
pH,524.0,NaN,NaN,NaN,7.3,4.7,7.2,7.3,7.5,8.1,0.3,0.0,0.0,0.0,0.0
ALC.,524.0,NaN,NaN,NaN,62.6,16.0,44.0,58.0,74.2,224.0,28.5,0.0,0.0,0.0,0.0
AC.,524.0,NaN,NaN,NaN,12.5,0.0,7.0,10.0,13.0,120.0,11.2,0.0,0.0,0.0,0.0
O.C.,524.0,NaN,NaN,NaN,8.9,3.0,6.3,7.8,9.8,84.0,5.6,0.0,0.0,0.0,0.0
O.D.,524.0,NaN,NaN,NaN,3.2,0.0,2.1,3.1,4.3,9.5,1.6,0.0,0.0,0.0,0.0
Cl,524.0,NaN,NaN,NaN,44.8,5.0,30.0,39.0,50.0,328.0,30.7,0.0,0.0,0.0,0.0
DUR.,524.0,NaN,NaN,NaN,54.1,10.0,40.0,50.0,62.0,170.0,22.4,0.0,0.0,0.0,0.0
Fe,524.0,NaN,NaN,NaN,2.33,0.09,0.81,1.28,2.80,18.00,2.56,0.0,0.0,0.0,0.0
Mn,524.0,NaN,NaN,NaN,0.20,0.01,0.10,0.15,0.21,1.64,0.19,0.0,0.0,0.0,0.0
Cond.,524.0,NaN,NaN,NaN,318.5,60.0,202.0,281.5,394.2,1438.0,172.6,0.0,0.0,0.0,0.0
Cianobacteria,524.0,NaN,NaN,NaN,8556.8,57.0,2353.0,4656.5,12010.2,45955.0,9554.0,0.0,0.0,0.0,0.0
C.F.,524.0,NaN,NaN,NaN,16426,100,2000,4200,17000,250850,33489,0.0,0.0,0.0,0.0
Clorofila,524.0,NaN,NaN,NaN,31.69,0.00,11.61,22.32,39.71,274.53,30.91,0.0,0.0,0.0,0.0
F,524.0,NaN,NaN,NaN,0.334,0.000,0.220,0.290,0.390,1.520,0.198,0.0,0.0,0.0,0.0

In [35]:
knn_lof_iqr_knn = imp.knn_imput(lof_iqr_knn, variaveis=variaveis)
ad.analise_descritiva(knn_lof_iqr_knn)

Valores faltantes após imputação KNN:
COR              0
TURB.            0
pH               0
ALC.             0
AC.              0
O.C.             0
O.D.             0
Cl               0
DUR.             0
Fe               0
Mn               0
Cond.            0
Cianobacteria    0
C.F.             0
Clorofila        0
F                0
dtype: int64
Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\imput_knn20260420_165335.xlsx
Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\describe20260420_165335.xlsx

c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['148.0' '185.2' '4.0' '46.0' '74.5' '177.0' '1220.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['102.6' '195.9' '1.0' '9.0' '21.0' '99.5' '1200.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['7.3' '0.3' '4.7' '7.2' '7.3' '7.5' '8.1']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['62.6' '28.5' '16.0' '44.0' '58.0' '74.2' '224.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['12.5' '11.2' '0.0' '7.0' '10.0' '13.0' '120.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['8.9' '5.6' '3.0' '6.3' '7.8' '9.8' '84.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['3.2' '1.6' '0.0' '2.1' '3.1' '4.3' '9.5']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['44.8' '30.7' '5.0' '30.0' '39.0' '50.0' '328.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['54.1' '22.4' '10.0' '40.0' '50.0' '62.0' '170.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['2.33' '2.56' '0.09' '0.81' '1.28' '2.80' '18.00']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.20' '0.19' '0.01' '0.10' '0.15' '0.21' '1.64']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['318.5' '172.6' '60.0' '202.0' '281.5' '394.2' '1438.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['8556.8' '9554.0' '57.0' '2353.0' '4656.5' '12010.2' '45955.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['16426' '33489' '100' '2000' '4200' '17000' '250850']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['31.69' '30.91' '0.00' '11.61' '22.32' '39.71' '274.53']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.334' '0.198' '0.000' '0.220' '0.290' '0.390' '1.520']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:79: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_apagar, metadados] = ''

,count,unique,top,freq,mean,min,25%,50%,75%,max,std,Porcentagem de Dados Faltantes,Numero de Dados Faltantes,Porcentagem de Dados Corrompidos,Numero de Dados Corrompidos
Index,524.0,NaN,,NaN,,,,,,,,,,,
Data,524,NaN,,NaN,,,,,,,,,,,
data_normalizada,524,180,,3,,,,,,,,,,,
Estatistica,524,3,,176,,,,,,,,,,,
COR,524.0,NaN,NaN,NaN,148.0,4.0,46.0,74.5,177.0,1220.0,185.2,0.0,0.0,0.0,0.0
TURB.,524.0,NaN,NaN,NaN,102.6,1.0,9.0,21.0,99.5,1200.0,195.9,0.0,0.0,0.0,0.0
pH,524.0,NaN,NaN,NaN,7.3,4.7,7.2,7.3,7.5,8.1,0.3,0.0,0.0,0.0,0.0
ALC.,524.0,NaN,NaN,NaN,62.6,16.0,44.0,58.0,74.2,224.0,28.5,0.0,0.0,0.0,0.0
AC.,524.0,NaN,NaN,NaN,12.5,0.0,7.0,10.0,13.0,120.0,11.2,0.0,0.0,0.0,0.0
O.C.,524.0,NaN,NaN,NaN,8.9,3.0,6.3,7.8,9.8,84.0,5.6,0.0,0.0,0.0,0.0
O.D.,524.0,NaN,NaN,NaN,3.2,0.0,2.1,3.1,4.3,9.5,1.6,0.0,0.0,0.0,0.0
Cl,524.0,NaN,NaN,NaN,44.8,5.0,30.0,39.0,50.0,328.0,30.7,0.0,0.0,0.0,0.0
DUR.,524.0,NaN,NaN,NaN,54.1,10.0,40.0,50.0,62.0,170.0,22.4,0.0,0.0,0.0,0.0
Fe,524.0,NaN,NaN,NaN,2.33,0.09,0.81,1.28,2.80,18.00,2.56,0.0,0.0,0.0,0.0
Mn,524.0,NaN,NaN,NaN,0.20,0.01,0.10,0.15,0.21,1.64,0.19,0.0,0.0,0.0,0.0
Cond.,524.0,NaN,NaN,NaN,318.5,60.0,202.0,281.5,394.2,1438.0,172.6,0.0,0.0,0.0,0.0
Cianobacteria,524.0,NaN,NaN,NaN,8556.8,57.0,2353.0,4656.5,12010.2,45955.0,9554.0,0.0,0.0,0.0,0.0
C.F.,524.0,NaN,NaN,NaN,16426,100,2000,4200,17000,250850,33489,0.0,0.0,0.0,0.0
Clorofila,524.0,NaN,NaN,NaN,31.69,0.00,11.61,22.32,39.71,274.53,30.91,0.0,0.0,0.0,0.0
F,524.0,NaN,NaN,NaN,0.334,0.000,0.220,0.290,0.390,1.520,0.198,0.0,0.0,0.0,0.0

In [36]:
media_lof_zscore_knn = imp.mean_imput(lof_zscore_knn, variaveis=variaveis)
ad.analise_descritiva(lof_zscore_knn)

Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\imput_mean20260420_165501.xlsx
Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\describe20260420_165501.xlsx

c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['148.0' '185.2' '4.0' '46.0' '74.5' '177.0' '1220.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['102.6' '195.9' '1.0' '9.0' '21.0' '99.5' '1200.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['7.3' '0.3' '4.7' '7.2' '7.3' '7.5' '8.1']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['62.6' '28.5' '16.0' '44.0' '58.0' '74.2' '224.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['12.5' '11.2' '0.0' '7.0' '10.0' '13.0' '120.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['8.9' '5.6' '3.0' '6.3' '7.8' '9.8' '84.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['3.2' '1.6' '0.0' '2.1' '3.1' '4.3' '9.5']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['44.8' '30.7' '5.0' '30.0' '39.0' '50.0' '328.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['54.1' '22.4' '10.0' '40.0' '50.0' '62.0' '170.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['2.33' '2.56' '0.09' '0.81' '1.28' '2.80' '18.00']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.20' '0.19' '0.01' '0.10' '0.15' '0.21' '1.64']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['318.5' '172.6' '60.0' '202.0' '281.5' '394.2' '1438.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['8556.8' '9554.0' '57.0' '2353.0' '4656.5' '12010.2' '45955.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['16426' '33489' '100' '2000' '4200' '17000' '250850']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['31.69' '30.91' '0.00' '11.61' '22.32' '39.71' '274.53']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.334' '0.198' '0.000' '0.220' '0.290' '0.390' '1.520']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:79: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_apagar, metadados] = ''

,count,unique,top,freq,mean,min,25%,50%,75%,max,std,Porcentagem de Dados Faltantes,Numero de Dados Faltantes,Porcentagem de Dados Corrompidos,Numero de Dados Corrompidos
Index,524.0,NaN,,NaN,,,,,,,,,,,
Data,524,NaN,,NaN,,,,,,,,,,,
data_normalizada,524,180,,3,,,,,,,,,,,
Estatistica,524,3,,176,,,,,,,,,,,
COR,524.0,NaN,NaN,NaN,148.0,4.0,46.0,74.5,177.0,1220.0,185.2,0.0,0.0,0.0,0.0
TURB.,524.0,NaN,NaN,NaN,102.6,1.0,9.0,21.0,99.5,1200.0,195.9,0.0,0.0,0.0,0.0
pH,524.0,NaN,NaN,NaN,7.3,4.7,7.2,7.3,7.5,8.1,0.3,0.0,0.0,0.0,0.0
ALC.,524.0,NaN,NaN,NaN,62.6,16.0,44.0,58.0,74.2,224.0,28.5,0.0,0.0,0.0,0.0
AC.,524.0,NaN,NaN,NaN,12.5,0.0,7.0,10.0,13.0,120.0,11.2,0.0,0.0,0.0,0.0
O.C.,524.0,NaN,NaN,NaN,8.9,3.0,6.3,7.8,9.8,84.0,5.6,0.0,0.0,0.0,0.0
O.D.,524.0,NaN,NaN,NaN,3.2,0.0,2.1,3.1,4.3,9.5,1.6,0.0,0.0,0.0,0.0
Cl,524.0,NaN,NaN,NaN,44.8,5.0,30.0,39.0,50.0,328.0,30.7,0.0,0.0,0.0,0.0
DUR.,524.0,NaN,NaN,NaN,54.1,10.0,40.0,50.0,62.0,170.0,22.4,0.0,0.0,0.0,0.0
Fe,524.0,NaN,NaN,NaN,2.33,0.09,0.81,1.28,2.80,18.00,2.56,0.0,0.0,0.0,0.0
Mn,524.0,NaN,NaN,NaN,0.20,0.01,0.10,0.15,0.21,1.64,0.19,0.0,0.0,0.0,0.0
Cond.,524.0,NaN,NaN,NaN,318.5,60.0,202.0,281.5,394.2,1438.0,172.6,0.0,0.0,0.0,0.0
Cianobacteria,524.0,NaN,NaN,NaN,8556.8,57.0,2353.0,4656.5,12010.2,45955.0,9554.0,0.0,0.0,0.0,0.0
C.F.,524.0,NaN,NaN,NaN,16426,100,2000,4200,17000,250850,33489,0.0,0.0,0.0,0.0
Clorofila,524.0,NaN,NaN,NaN,31.69,0.00,11.61,22.32,39.71,274.53,30.91,0.0,0.0,0.0,0.0
F,524.0,NaN,NaN,NaN,0.334,0.000,0.220,0.290,0.390,1.520,0.198,0.0,0.0,0.0,0.0

In [37]:
mediana_lof_zscore_knn = imp.median_imput(lof_zscore_knn, variaveis=variaveis)
ad.analise_descritiva(mediana_lof_iqr_knn)

Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\imput_median20260420_165617.xlsx
Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\describe20260420_165618.xlsx

c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['148.0' '185.2' '4.0' '46.0' '74.5' '177.0' '1220.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['102.6' '195.9' '1.0' '9.0' '21.0' '99.5' '1200.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['7.3' '0.3' '4.7' '7.2' '7.3' '7.5' '8.1']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['62.6' '28.5' '16.0' '44.0' '58.0' '74.2' '224.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['12.5' '11.2' '0.0' '7.0' '10.0' '13.0' '120.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['8.9' '5.6' '3.0' '6.3' '7.8' '9.8' '84.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['3.2' '1.6' '0.0' '2.1' '3.1' '4.3' '9.5']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['44.8' '30.7' '5.0' '30.0' '39.0' '50.0' '328.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['54.1' '22.4' '10.0' '40.0' '50.0' '62.0' '170.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['2.33' '2.56' '0.09' '0.81' '1.28' '2.80' '18.00']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.20' '0.19' '0.01' '0.10' '0.15' '0.21' '1.64']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['318.5' '172.6' '60.0' '202.0' '281.5' '394.2' '1438.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['8556.8' '9554.0' '57.0' '2353.0' '4656.5' '12010.2' '45955.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['16426' '33489' '100' '2000' '4200' '17000' '250850']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['31.69' '30.91' '0.00' '11.61' '22.32' '39.71' '274.53']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.334' '0.198' '0.000' '0.220' '0.290' '0.390' '1.520']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:79: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_apagar, metadados] = ''

,count,unique,top,freq,mean,min,25%,50%,75%,max,std,Porcentagem de Dados Faltantes,Numero de Dados Faltantes,Porcentagem de Dados Corrompidos,Numero de Dados Corrompidos
Index,524.0,NaN,,NaN,,,,,,,,,,,
Data,524,NaN,,NaN,,,,,,,,,,,
data_normalizada,524,180,,3,,,,,,,,,,,
Estatistica,524,3,,176,,,,,,,,,,,
COR,524.0,NaN,NaN,NaN,148.0,4.0,46.0,74.5,177.0,1220.0,185.2,0.0,0.0,0.0,0.0
TURB.,524.0,NaN,NaN,NaN,102.6,1.0,9.0,21.0,99.5,1200.0,195.9,0.0,0.0,0.0,0.0
pH,524.0,NaN,NaN,NaN,7.3,4.7,7.2,7.3,7.5,8.1,0.3,0.0,0.0,0.0,0.0
ALC.,524.0,NaN,NaN,NaN,62.6,16.0,44.0,58.0,74.2,224.0,28.5,0.0,0.0,0.0,0.0
AC.,524.0,NaN,NaN,NaN,12.5,0.0,7.0,10.0,13.0,120.0,11.2,0.0,0.0,0.0,0.0
O.C.,524.0,NaN,NaN,NaN,8.9,3.0,6.3,7.8,9.8,84.0,5.6,0.0,0.0,0.0,0.0
O.D.,524.0,NaN,NaN,NaN,3.2,0.0,2.1,3.1,4.3,9.5,1.6,0.0,0.0,0.0,0.0
Cl,524.0,NaN,NaN,NaN,44.8,5.0,30.0,39.0,50.0,328.0,30.7,0.0,0.0,0.0,0.0
DUR.,524.0,NaN,NaN,NaN,54.1,10.0,40.0,50.0,62.0,170.0,22.4,0.0,0.0,0.0,0.0
Fe,524.0,NaN,NaN,NaN,2.33,0.09,0.81,1.28,2.80,18.00,2.56,0.0,0.0,0.0,0.0
Mn,524.0,NaN,NaN,NaN,0.20,0.01,0.10,0.15,0.21,1.64,0.19,0.0,0.0,0.0,0.0
Cond.,524.0,NaN,NaN,NaN,318.5,60.0,202.0,281.5,394.2,1438.0,172.6,0.0,0.0,0.0,0.0
Cianobacteria,524.0,NaN,NaN,NaN,8556.8,57.0,2353.0,4656.5,12010.2,45955.0,9554.0,0.0,0.0,0.0,0.0
C.F.,524.0,NaN,NaN,NaN,16426,100,2000,4200,17000,250850,33489,0.0,0.0,0.0,0.0
Clorofila,524.0,NaN,NaN,NaN,31.69,0.00,11.61,22.32,39.71,274.53,30.91,0.0,0.0,0.0,0.0
F,524.0,NaN,NaN,NaN,0.334,0.000,0.220,0.290,0.390,1.520,0.198,0.0,0.0,0.0,0.0

In [38]:
knn_lof_zscore_knn = imp.knn_imput(lof_zscore_knn, variaveis=variaveis)
ad.analise_descritiva(lof_zscore_knn)

Valores faltantes após imputação KNN:
COR              0
TURB.            0
pH               0
ALC.             0
AC.              0
O.C.             0
O.D.             0
Cl               0
DUR.             0
Fe               0
Mn               0
Cond.            0
Cianobacteria    0
C.F.             0
Clorofila        0
F                0
dtype: int64
Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\imput_knn20260420_165707.xlsx
Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\describe20260420_165707.xlsx

c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['148.0' '185.2' '4.0' '46.0' '74.5' '177.0' '1220.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['102.6' '195.9' '1.0' '9.0' '21.0' '99.5' '1200.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['7.3' '0.3' '4.7' '7.2' '7.3' '7.5' '8.1']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['62.6' '28.5' '16.0' '44.0' '58.0' '74.2' '224.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['12.5' '11.2' '0.0' '7.0' '10.0' '13.0' '120.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['8.9' '5.6' '3.0' '6.3' '7.8' '9.8' '84.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['3.2' '1.6' '0.0' '2.1' '3.1' '4.3' '9.5']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['44.8' '30.7' '5.0' '30.0' '39.0' '50.0' '328.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['54.1' '22.4' '10.0' '40.0' '50.0' '62.0' '170.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['2.33' '2.56' '0.09' '0.81' '1.28' '2.80' '18.00']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.20' '0.19' '0.01' '0.10' '0.15' '0.21' '1.64']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['318.5' '172.6' '60.0' '202.0' '281.5' '394.2' '1438.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['8556.8' '9554.0' '57.0' '2353.0' '4656.5' '12010.2' '45955.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['16426' '33489' '100' '2000' '4200' '17000' '250850']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['31.69' '30.91' '0.00' '11.61' '22.32' '39.71' '274.53']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:59: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.334' '0.198' '0.000' '0.220' '0.290' '0.390' '1.520']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, i] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\format.py:79: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_apagar, metadados] = ''

,count,unique,top,freq,mean,min,25%,50%,75%,max,std,Porcentagem de Dados Faltantes,Numero de Dados Faltantes,Porcentagem de Dados Corrompidos,Numero de Dados Corrompidos
Index,524.0,NaN,,NaN,,,,,,,,,,,
Data,524,NaN,,NaN,,,,,,,,,,,
data_normalizada,524,180,,3,,,,,,,,,,,
Estatistica,524,3,,176,,,,,,,,,,,
COR,524.0,NaN,NaN,NaN,148.0,4.0,46.0,74.5,177.0,1220.0,185.2,0.0,0.0,0.0,0.0
TURB.,524.0,NaN,NaN,NaN,102.6,1.0,9.0,21.0,99.5,1200.0,195.9,0.0,0.0,0.0,0.0
pH,524.0,NaN,NaN,NaN,7.3,4.7,7.2,7.3,7.5,8.1,0.3,0.0,0.0,0.0,0.0
ALC.,524.0,NaN,NaN,NaN,62.6,16.0,44.0,58.0,74.2,224.0,28.5,0.0,0.0,0.0,0.0
AC.,524.0,NaN,NaN,NaN,12.5,0.0,7.0,10.0,13.0,120.0,11.2,0.0,0.0,0.0,0.0
O.C.,524.0,NaN,NaN,NaN,8.9,3.0,6.3,7.8,9.8,84.0,5.6,0.0,0.0,0.0,0.0
O.D.,524.0,NaN,NaN,NaN,3.2,0.0,2.1,3.1,4.3,9.5,1.6,0.0,0.0,0.0,0.0
Cl,524.0,NaN,NaN,NaN,44.8,5.0,30.0,39.0,50.0,328.0,30.7,0.0,0.0,0.0,0.0
DUR.,524.0,NaN,NaN,NaN,54.1,10.0,40.0,50.0,62.0,170.0,22.4,0.0,0.0,0.0,0.0
Fe,524.0,NaN,NaN,NaN,2.33,0.09,0.81,1.28,2.80,18.00,2.56,0.0,0.0,0.0,0.0
Mn,524.0,NaN,NaN,NaN,0.20,0.01,0.10,0.15,0.21,1.64,0.19,0.0,0.0,0.0,0.0
Cond.,524.0,NaN,NaN,NaN,318.5,60.0,202.0,281.5,394.2,1438.0,172.6,0.0,0.0,0.0,0.0
Cianobacteria,524.0,NaN,NaN,NaN,8556.8,57.0,2353.0,4656.5,12010.2,45955.0,9554.0,0.0,0.0,0.0,0.0
C.F.,524.0,NaN,NaN,NaN,16426,100,2000,4200,17000,250850,33489,0.0,0.0,0.0,0.0
Clorofila,524.0,NaN,NaN,NaN,31.69,0.00,11.61,22.32,39.71,274.53,30.91,0.0,0.0,0.0,0.0
F,524.0,NaN,NaN,NaN,0.334,0.000,0.220,0.290,0.390,1.520,0.198,0.0,0.0,0.0,0.0