In [1]:
import sys
from pathlib import Path
sys.path.append(str(Path.cwd().parent))

import utils as uti
import visualizacoes as vis
import analise_descritiva as ad
import limpeza as lpz
import outliers as out
import imputacao as imp

In [7]:
dados_limpos, metadados, variaveis = uti.dados(r"data\out\dados_limpos20260410_165530.xlsx")

ad.analise_descritiva(dados_limpos, variaveis=variaveis, metadados=metadados)

Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\describe20260410_181334.xlsx

c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['149.3' '192.2' '4.0' '46.0' '74.0' '171.0' '1650.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['102.2' '196.5' '1.0' '9.0' '21.0' '92.0' '1200.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['7.3' '0.3' '4.7' '7.2' '7.3' '7.5' '8.1']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['63.6' '30.9' '16.0' '44.0' '57.5' '75.8' '224.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['12.5' '11.7' '0.0' '7.0' '10.0' '13.0' '120.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['9.1' '5.7' '2.3' '6.3' '7.8' '10.2' '84.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['3.2' '1.6' '0.0' '2.1' '3.1' '4.3' '9.5']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['45.3' '31.0' '5.0' '30.0' '39.0' '51.0' '328.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['55.2' '23.8' '10.0' '40.0' '50.0' '64.0' '174.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['2.39' '2.74' '0.09' '0.83' '1.28' '2.83' '26.00']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.21' '0.21' '0.01' '0.11' '0.15' '0.22' '2.36']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['325.7' '180.5' '60.0' '202.5' '283.0' '403.0' '1438.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['10527.4' '14958.8' '57.0' '2064.0' '4964.0' '13364.0' '122480.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['23842.6' '53343.4' '0.0' '2200.0' '5400.0' '19000.0' '500000.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['36.54' '47.75' '0.00' '12.28' '25.29' '47.17' '509.64']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.314' '0.202' '0.000' '0.198' '0.280' '0.380' '1.520']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:156: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_apagar, metadados] = ''

,count,unique,top,freq,mean,min,25%,50%,75%,max,std,Porcentagem de Dados Faltantes,Numero de Dados Faltantes,Porcentagem de Dados Corrompidos,Numero de Dados Corrompidos
Index,576.0,NaN,,NaN,,,,,,,,,,,
Data,576,NaN,,NaN,,,,,,,,,,,
data_normalizada,576,NaN,,NaN,,,,,,,,,,,
Estatistica,576,3,,192,,,,,,,,,,,
COR,573.0,NaN,NaN,NaN,149.3,4.0,46.0,74.0,171.0,1650.0,192.2,0.52,3.0,0.0,0.0
TURB.,573.0,NaN,NaN,NaN,102.2,1.0,9.0,21.0,92.0,1200.0,196.5,0.52,3.0,0.0,0.0
pH,573.0,NaN,NaN,NaN,7.3,4.7,7.2,7.3,7.5,8.1,0.3,0.52,3.0,0.0,0.0
ALC.,546.0,NaN,NaN,NaN,63.6,16.0,44.0,57.5,75.8,224.0,30.9,5.21,30.0,0.0,0.0
AC.,546.0,NaN,NaN,NaN,12.5,0.0,7.0,10.0,13.0,120.0,11.7,5.21,30.0,0.0,0.0
O.C.,555.0,NaN,NaN,NaN,9.1,2.3,6.3,7.8,10.2,84.0,5.7,3.65,21.0,0.0,0.0
O.D.,560.0,NaN,NaN,NaN,3.2,0.0,2.1,3.1,4.3,9.5,1.6,2.78,16.0,0.0,0.0
Cl,555.0,NaN,NaN,NaN,45.3,5.0,30.0,39.0,51.0,328.0,31.0,3.65,21.0,0.0,0.0
DUR.,555.0,NaN,NaN,NaN,55.2,10.0,40.0,50.0,64.0,174.0,23.8,3.65,21.0,0.0,0.0
Fe,555.0,NaN,NaN,NaN,2.39,0.09,0.83,1.28,2.83,26.00,2.74,3.65,21.0,0.0,0.0
Mn,555.0,NaN,NaN,NaN,0.21,0.01,0.11,0.15,0.22,2.36,0.21,3.65,21.0,0.0,0.0
Cond.,567.0,NaN,NaN,NaN,325.7,60.0,202.5,283.0,403.0,1438.0,180.5,1.56,9.0,0.0,0.0
Cianobacteria,534.0,NaN,NaN,NaN,10527.4,57.0,2064.0,4964.0,13364.0,122480.0,14958.8,7.29,42.0,0.0,0.0
C.F.,461.0,NaN,NaN,NaN,23842.6,0.0,2200.0,5400.0,19000.0,500000.0,53343.4,19.97,115.0,0.0,0.0
Clorofila,531.0,NaN,NaN,NaN,36.54,0.00,12.28,25.29,47.17,509.64,47.75,7.81,45.0,0.0,0.0
F,468.0,NaN,NaN,NaN,0.314,0.000,0.198,0.280,0.380,1.520,0.202,18.75,108.0,0.0,0.0

In [9]:
out.detect_outliers(dados_limpos, variaveis=variaveis, methods='zscore')

out.remove_outliers_zscore(dados_limpos, variaveis=variaveis)

ad.analise_descritiva(dados_limpos, variaveis=variaveis, metadados=metadados)

Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\outliers_removed_zscore20260410_181347.xlsx
Arquivo salvo em: C:\_Master\Programacao\Guilherme-Betta\IC2\data\out\describe20260410_181347.xlsx

c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['149.3' '192.2' '4.0' '46.0' '74.0' '171.0' '1650.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['102.2' '196.5' '1.0' '9.0' '21.0' '92.0' '1200.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['7.3' '0.3' '4.7' '7.2' '7.3' '7.5' '8.1']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['63.6' '30.9' '16.0' '44.0' '57.5' '75.8' '224.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['12.5' '11.7' '0.0' '7.0' '10.0' '13.0' '120.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['9.1' '5.7' '2.3' '6.3' '7.8' '10.2' '84.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['3.2' '1.6' '0.0' '2.1' '3.1' '4.3' '9.5']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['45.3' '31.0' '5.0' '30.0' '39.0' '51.0' '328.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['55.2' '23.8' '10.0' '40.0' '50.0' '64.0' '174.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['2.39' '2.74' '0.09' '0.83' '1.28' '2.83' '26.00']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.21' '0.21' '0.01' '0.11' '0.15' '0.22' '2.36']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['325.7' '180.5' '60.0' '202.5' '283.0' '403.0' '1438.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['10527.4' '14958.8' '57.0' '2064.0' '4964.0' '13364.0' '122480.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['23842.6' '53343.4' '0.0' '2200.0' '5400.0' '19000.0' '500000.0']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['36.54' '47.75' '0.00' '12.28' '25.29' '47.17' '509.64']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:136: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['0.314' '0.202' '0.000' '0.198' '0.280' '0.380' '1.520']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_para_formatar, col] = dados_matematicos.apply(
c:\_Master\programacao\Guilherme-Betta\IC2\analise_descritiva.py:156: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  describe.loc[estatisticas_apagar, metadados] = ''

,count,unique,top,freq,mean,min,25%,50%,75%,max,std,Porcentagem de Dados Faltantes,Numero de Dados Faltantes,Porcentagem de Dados Corrompidos,Numero de Dados Corrompidos
Index,576.0,NaN,,NaN,,,,,,,,,,,
Data,576,NaN,,NaN,,,,,,,,,,,
data_normalizada,576,NaN,,NaN,,,,,,,,,,,
Estatistica,576,3,,192,,,,,,,,,,,
COR,573.0,NaN,NaN,NaN,149.3,4.0,46.0,74.0,171.0,1650.0,192.2,0.52,3.0,0.0,0.0
TURB.,573.0,NaN,NaN,NaN,102.2,1.0,9.0,21.0,92.0,1200.0,196.5,0.52,3.0,0.0,0.0
pH,573.0,NaN,NaN,NaN,7.3,4.7,7.2,7.3,7.5,8.1,0.3,0.52,3.0,0.0,0.0
ALC.,546.0,NaN,NaN,NaN,63.6,16.0,44.0,57.5,75.8,224.0,30.9,5.21,30.0,0.0,0.0
AC.,546.0,NaN,NaN,NaN,12.5,0.0,7.0,10.0,13.0,120.0,11.7,5.21,30.0,0.0,0.0
O.C.,555.0,NaN,NaN,NaN,9.1,2.3,6.3,7.8,10.2,84.0,5.7,3.65,21.0,0.0,0.0
O.D.,560.0,NaN,NaN,NaN,3.2,0.0,2.1,3.1,4.3,9.5,1.6,2.78,16.0,0.0,0.0
Cl,555.0,NaN,NaN,NaN,45.3,5.0,30.0,39.0,51.0,328.0,31.0,3.65,21.0,0.0,0.0
DUR.,555.0,NaN,NaN,NaN,55.2,10.0,40.0,50.0,64.0,174.0,23.8,3.65,21.0,0.0,0.0
Fe,555.0,NaN,NaN,NaN,2.39,0.09,0.83,1.28,2.83,26.00,2.74,3.65,21.0,0.0,0.0
Mn,555.0,NaN,NaN,NaN,0.21,0.01,0.11,0.15,0.22,2.36,0.21,3.65,21.0,0.0,0.0
Cond.,567.0,NaN,NaN,NaN,325.7,60.0,202.5,283.0,403.0,1438.0,180.5,1.56,9.0,0.0,0.0
Cianobacteria,534.0,NaN,NaN,NaN,10527.4,57.0,2064.0,4964.0,13364.0,122480.0,14958.8,7.29,42.0,0.0,0.0
C.F.,461.0,NaN,NaN,NaN,23842.6,0.0,2200.0,5400.0,19000.0,500000.0,53343.4,19.97,115.0,0.0,0.0
Clorofila,531.0,NaN,NaN,NaN,36.54,0.00,12.28,25.29,47.17,509.64,47.75,7.81,45.0,0.0,0.0
F,468.0,NaN,NaN,NaN,0.314,0.000,0.198,0.280,0.380,1.520,0.202,18.75,108.0,0.0,0.0