In [1]:
from pcj.utils import dados
from pcj.processamento import decompor_estatisticas
from pcj.metricas_avaliacao import avaliacao_completa

In [2]:
df, metadados, variaveis = dados(r"data\processed\dados_limpos.xlsx")

In [3]:
df_min, df_med, df_max = decompor_estatisticas(df)

In [4]:
avaliacao_completa(df_min)

16 colunas, 5.0% removido
Colunas usadas para métricas: ['Cl', 'Cianobacteria', 'TURB.', 'Mn', 'pH', 'Clorofila', 'ALC.', 'Fe', 'C.F.', 'AC.', 'COR', 'O.C.', 'O.D.', 'Cond.', 'F', 'DUR.']
Total de colunas: 16
Colunas usadas para métricas: ['Cl', 'Cianobacteria', 'TURB.', 'Mn', 'pH', 'Clorofila', 'ALC.', 'Fe', 'C.F.', 'AC.', 'COR', 'O.C.', 'O.D.', 'Cond.', 'F', 'DUR.']
Total de colunas: 16
16 colunas, 30.0% removido
Valores faltantes após imputação KNN:
COR              0
TURB.            0
pH               0
ALC.             0
AC.              0
O.C.             0
O.D.             0
Cl               0
DUR.             0
Fe               0
Mn               0
Cond.            0
Cianobacteria    0
C.F.             0
Clorofila        0
F                0
dtype: int64
Colunas usadas para métricas: ['Cl', 'Cianobacteria', 'TURB.', 'Mn', 'pH', 'Clorofila', 'ALC.', 'Fe', 'C.F.', 'AC.', 'COR', 'O.C.', 'O.D.', 'Cond.', 'F', 'DUR.']
Total de colunas: 16

,variavel,rmse,mae,r2,n_celulas,metodo,pct_faltantes
0,Cl,36.058133,25.225000,-0.332312,6,media,0.05
1,Cianobacteria,6037.789579,5732.516667,-9.145651,6,media,0.05
2,TURB.,32.108190,21.033333,-0.015367,6,media,0.05
3,Mn,0.033517,0.028333,-0.008535,6,media,0.05
4,pH,0.264764,0.206667,-0.802571,6,media,0.05
5,Clorofila,17.174733,15.536667,-1.389846,6,media,0.05
6,ALC.,35.636094,25.647222,-0.111240,6,media,0.05
7,Fe,0.910625,0.616556,-0.014000,6,media,0.05
8,C.F.,62702.101418,34027.666667,-0.073436,6,media,0.05
9,AC.,3.528072,2.941667,-0.217670,6,media,0.05
10,COR,50.079576,37.830556,-0.003230,6,media,0.05
11,O.C.,3.342371,2.354444,-0.280803,6,media,0.05
12,O.D.,0.761315,0.716667,-0.000749,6,media,0.05
13,Cond.,72.468396,65.763889,-0.094478,6,media,0.05
14,F,0.111068,0.097222,-0.445638,6,media,0.05
15,DUR.,20.393381,15.200000,-0.482380,6,media,0.05
16,Cl,36.737810,25.666667,-0.383013,6,mediana,0.05
17,Cianobacteria,1901.606667,1823.333333,-0.006388,6,mediana,0.05
18,TURB.,33.709544,17.000000,-0.119173,6,mediana,0.05
19,Mn,0.034400,0.028333,-0.062344,6,mediana,0.05
20,pH,0.258199,0.200000,-0.714286,6,mediana,0.05
21,Clorofila,11.131486,9.005000,-0.003913,6,mediana,0.05
22,ALC.,36.916573,26.833333,-0.192533,6,mediana,0.05
23,Fe,1.031730,0.653333,-0.301640,6,mediana,0.05
24,C.F.,67598.828885,31583.333333,-0.247643,6,mediana,0.05
25,AC.,3.605551,3.000000,-0.271739,6,mediana,0.05
26,COR,52.152820,36.666667,-0.088015,6,mediana,0.05
27,O.C.,3.240370,2.200000,-0.203822,6,mediana,0.05
28,O.D.,0.762671,0.716667,-0.004317,6,mediana,0.05
29,Cond.,69.488009,61.000000,-0.006304,6,mediana,0.05
30,F,0.107510,0.095000,-0.354492,6,mediana,0.05
31,DUR.,22.045408,17.000000,-0.732277,6,mediana,0.05
32,Cl,19.813488,13.851351,-0.146698,37,knn,0.30
33,Cianobacteria,12653.407680,6515.162162,0.088445,37,knn,0.30
34,TURB.,21.463514,14.094595,0.107253,37,knn,0.30
35,Mn,0.046651,0.036351,-0.149824,37,knn,0.30
36,pH,0.241896,0.186486,-0.134953,37,knn,0.30
37,Clorofila,34.034242,25.795405,-0.227719,37,knn,0.30
38,ALC.,21.238829,15.527027,-0.110642,37,knn,0.30
39,Fe,0.928224,0.633514,-0.106605,37,knn,0.30
40,C.F.,39364.757664,19354.054054,-0.169635,37,knn,0.30
41,AC.,5.149784,3.391892,-2.586865,37,knn,0.30
42,COR,71.941887,46.297297,-0.205843,37,knn,0.30
43,O.C.,1.963846,1.539189,-0.032596,37,knn,0.30
44,O.D.,1.259343,1.002703,-0.065130,37,knn,0.30
45,Cond.,109.327150,86.554054,-0.019310,37,knn,0.30
46,F,0.087402,0.070000,-0.336355,37,knn,0.30
47,DUR.,16.497543,12.445946,-0.214881,37,knn,0.30

In [5]:
avaliacao_completa(df_med)

16 colunas, 5.0% removido
Colunas usadas para métricas: ['Cl', 'Cianobacteria', 'TURB.', 'Mn', 'pH', 'Clorofila', 'ALC.', 'Fe', 'C.F.', 'AC.', 'COR', 'O.C.', 'O.D.', 'Cond.', 'F', 'DUR.']
Total de colunas: 16
Colunas usadas para métricas: ['Cl', 'Cianobacteria', 'TURB.', 'Mn', 'pH', 'Clorofila', 'ALC.', 'Fe', 'C.F.', 'AC.', 'COR', 'O.C.', 'O.D.', 'Cond.', 'F', 'DUR.']
Total de colunas: 16
16 colunas, 30.0% removido
Valores faltantes após imputação KNN:
COR              0
TURB.            0
pH               0
ALC.             0
AC.              0
O.C.             0
O.D.             0
Cl               0
DUR.             0
Fe               0
Mn               0
Cond.            0
Cianobacteria    0
C.F.             0
Clorofila        0
F                0
dtype: int64
Colunas usadas para métricas: ['Cl', 'Cianobacteria', 'TURB.', 'Mn', 'pH', 'Clorofila', 'ALC.', 'Fe', 'C.F.', 'AC.', 'COR', 'O.C.', 'O.D.', 'Cond.', 'F', 'DUR.']
Total de colunas: 16

,variavel,rmse,mae,r2,n_celulas,metodo,pct_faltantes
0,Cl,80.416720,50.244444,-0.360614,6,media,0.05
1,Cianobacteria,6106.508745,5611.525000,-5.428954,6,media,0.05
2,TURB.,95.811047,69.644444,-0.000204,6,media,0.05
3,Mn,0.053148,0.046167,-2.259303,6,media,0.05
4,pH,0.172982,0.152500,-3.488438,6,media,0.05
5,Clorofila,14.831175,13.997389,-1.749917,6,media,0.05
6,ALC.,35.300221,25.833333,-0.140977,6,media,0.05
7,Fe,2.073971,1.788389,-0.023079,6,media,0.05
8,C.F.,61691.434153,36982.111111,-0.039110,6,media,0.05
9,AC.,4.993913,3.550000,-0.019081,6,media,0.05
10,COR,79.901728,74.105556,-0.288829,6,media,0.05
11,O.C.,2.805065,2.224722,-0.098724,6,media,0.05
12,O.D.,0.976486,0.950000,-0.011698,6,media,0.05
13,Cond.,89.735198,76.733333,-0.486895,6,media,0.05
14,F,0.146483,0.110989,-1.328801,6,media,0.05
15,DUR.,18.848978,13.833333,-0.111710,6,media,0.05
16,Cl,82.146211,51.333333,-0.419768,6,mediana,0.05
17,Cianobacteria,2438.188450,2217.166667,-0.024917,6,mediana,0.05
18,TURB.,101.767709,54.666667,-0.128437,6,mediana,0.05
19,Mn,0.031091,0.026667,-0.115385,6,mediana,0.05
20,pH,0.216025,0.200000,-6.000000,6,mediana,0.05
21,Clorofila,9.014773,7.006667,-0.015963,6,mediana,0.05
22,ALC.,37.240211,25.833333,-0.269832,6,mediana,0.05
23,Fe,2.332408,1.686667,-0.293936,6,mediana,0.05
24,C.F.,67399.548713,31433.333333,-0.240298,6,mediana,0.05
25,AC.,5.700877,3.833333,-0.328036,6,mediana,0.05
26,COR,71.369344,50.666667,-0.028268,6,mediana,0.05
27,O.C.,2.899713,2.350000,-0.174120,6,mediana,0.05
28,O.D.,0.982344,0.950000,-0.023873,6,mediana,0.05
29,Cond.,76.953449,65.500000,-0.093480,6,mediana,0.05
30,F,0.139821,0.105000,-1.121797,6,mediana,0.05
31,DUR.,20.483733,15.833333,-0.312907,6,mediana,0.05
32,Cl,38.800164,20.986486,-0.112902,37,knn,0.30
33,Cianobacteria,14760.328060,8202.662162,-0.253729,37,knn,0.30
34,TURB.,75.646091,57.202703,-0.223109,37,knn,0.30
35,Mn,0.089726,0.062297,-0.408770,37,knn,0.30
36,pH,0.181026,0.147297,-0.027542,37,knn,0.30
37,Clorofila,33.688999,25.929054,-0.228975,37,knn,0.30
38,ALC.,19.150894,13.540541,0.295617,37,knn,0.30
39,Fe,1.286465,0.916622,0.381952,37,knn,0.30
40,C.F.,46632.416822,24140.270270,-0.560282,37,knn,0.30
41,AC.,7.608672,5.189189,-0.862171,37,knn,0.30
42,COR,141.764246,85.716216,0.145622,37,knn,0.30
43,O.C.,2.765558,1.841892,0.123093,37,knn,0.30
44,O.D.,1.210679,1.047297,-0.100521,37,knn,0.30
45,Cond.,141.224663,100.162162,0.230677,37,knn,0.30
46,F,0.134754,0.101108,-0.558181,37,knn,0.30
47,DUR.,18.693112,14.783784,-0.253165,37,knn,0.30

In [6]:
avaliacao_completa(df_max)

16 colunas, 5.0% removido
Colunas usadas para métricas: ['Cl', 'Cianobacteria', 'TURB.', 'Mn', 'pH', 'Clorofila', 'ALC.', 'Fe', 'C.F.', 'AC.', 'COR', 'O.C.', 'O.D.', 'Cond.', 'F', 'DUR.']
Total de colunas: 16
Colunas usadas para métricas: ['Cl', 'Cianobacteria', 'TURB.', 'Mn', 'pH', 'Clorofila', 'ALC.', 'Fe', 'C.F.', 'AC.', 'COR', 'O.C.', 'O.D.', 'Cond.', 'F', 'DUR.']
Total de colunas: 16
16 colunas, 30.0% removido
Valores faltantes após imputação KNN:
COR              0
TURB.            0
pH               0
ALC.             0
AC.              0
O.C.             0
O.D.             0
Cl               0
DUR.             0
Fe               0
Mn               0
Cond.            0
Cianobacteria    0
C.F.             0
Clorofila        0
F                0
dtype: int64
Colunas usadas para métricas: ['Cl', 'Cianobacteria', 'TURB.', 'Mn', 'pH', 'Clorofila', 'ALC.', 'Fe', 'C.F.', 'AC.', 'COR', 'O.C.', 'O.D.', 'Cond.', 'F', 'DUR.']
Total de colunas: 16

,variavel,rmse,mae,r2,n_celulas,metodo,pct_faltantes
0,Cl,104.458135,66.600840,-0.305494,6,media,0.05
1,Cianobacteria,9296.674138,9271.610644,-0.124451,6,media,0.05
2,TURB.,168.027928,153.224090,-0.843873,6,media,0.05
3,Mn,0.121207,0.110000,-0.032965,6,media,0.05
4,pH,0.140546,0.133193,-0.734427,6,media,0.05
5,Clorofila,17.048251,15.036106,-0.725599,6,media,0.05
6,ALC.,44.616317,37.991597,-0.465964,6,media,0.05
7,Fe,3.127092,3.058403,-0.046901,6,media,0.05
8,C.F.,24054.004085,23519.229692,-21.742672,6,media,0.05
9,AC.,4.082074,3.179272,-1.541863,6,media,0.05
10,COR,346.256517,244.924370,-0.006850,6,media,0.05
11,O.C.,5.602552,4.673669,-0.039166,6,media,0.05
12,O.D.,1.619351,1.503221,-1.785562,6,media,0.05
13,Cond.,134.767359,111.861345,-0.340439,6,media,0.05
14,F,0.235790,0.209860,-3.811257,6,media,0.05
15,DUR.,19.848062,15.000000,-0.065038,6,media,0.05
16,Cl,108.717524,65.833333,-0.414131,6,mediana,0.05
17,Cianobacteria,9171.705221,7342.666667,-0.094424,6,mediana,0.05
18,TURB.,127.094453,105.666667,-0.054924,6,mediana,0.05
19,Mn,0.160000,0.130000,-0.800000,6,mediana,0.05
20,pH,0.108012,0.083333,-0.024390,6,mediana,0.05
21,Clorofila,12.979657,11.283333,-0.000245,6,mediana,0.05
22,ALC.,49.913258,43.666667,-0.834711,6,mediana,0.05
23,Fe,3.150127,2.583333,-0.062381,6,mediana,0.05
24,C.F.,5703.105879,5195.000000,-0.278467,6,mediana,0.05
25,AC.,2.886751,2.666667,-0.271186,6,mediana,0.05
26,COR,367.475169,244.333333,-0.134031,6,mediana,0.05
27,O.C.,6.445153,5.433333,-0.375244,6,mediana,0.05
28,O.D.,1.479302,1.383333,-1.324580,6,mediana,0.05
29,Cond.,121.219498,101.833333,-0.084483,6,mediana,0.05
30,F,0.198326,0.166667,-2.403846,6,mediana,0.05
31,DUR.,19.304576,15.000000,-0.007510,6,mediana,0.05
32,Cl,60.251444,34.337838,-0.132919,37,knn,0.30
33,Cianobacteria,14804.510847,10176.229730,-0.339029,37,knn,0.30
34,TURB.,234.381749,129.175676,0.080579,37,knn,0.30
35,Mn,0.410601,0.212973,-0.052654,37,knn,0.30
36,pH,0.198474,0.166216,-0.909614,37,knn,0.30
37,Clorofila,28.099588,18.785946,0.012898,37,knn,0.30
38,ALC.,33.114768,21.094595,0.063807,37,knn,0.30
39,Fe,3.064644,2.153919,0.403822,37,knn,0.30
40,C.F.,64342.792704,33538.378378,-0.700746,37,knn,0.30
41,AC.,9.034842,6.608108,-0.447867,37,knn,0.30
42,COR,338.176060,202.500000,-0.011221,37,knn,0.30
43,O.C.,14.397982,7.500000,-0.049355,37,knn,0.30
44,O.D.,1.464720,1.175676,-0.125802,37,knn,0.30
45,Cond.,222.503219,152.932432,-0.196263,37,knn,0.30
46,F,0.259780,0.163378,-0.113692,37,knn,0.30
47,DUR.,35.851420,25.432432,-0.702434,37,knn,0.30